### ISSUE TITLE
Can't get over email

### ISSUE THREAD

**Issue by mkdizajn** [wrr/wwwhisper-openshift#1]
Hi this is little excert from cli where I get stuck:

///

```
remote: Cleaning up...
remote: ~/diy-0.1/runtime ~/git/nginxpersona.git
remote: ~/git/nginxpersona.git
remote:           ============================================================
remote:           FATAL: You need to set INITIAL_ADMIN_EMAIL in etc/site.conf.
remote:           ============================================================
remote: Running .openshift/action_hooks/deploy
remote: Activating virtualenv
remote: ~/app-root/runtime/repo/blog ~/git/nginxpersona.git
remote: Generating static blog files.
remote: /var/lib/openshift/cc27674a737248cea1b9d23f353b2414/app-root/runtime/repo/.openshift/action_hooks/deploy: line 17: tinker: command not found
remote: hot_deploy_added=false
remote: Preprocessing nginx config.
remote: Starting nginx.
remote: Activating virtualenv
remote: Starting uwsgi for wwwhisper.
remote: open("./python_plugin.so"): No such file or directory [core/utils.c line 4695]
remote: !!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!

```

///

this is in my /etc/site.conf

INITIAL_ADMIN_EMAIL="my-email-un@gmail.com"

and this is my second time with misc/rebuild after misc/start_over

I get error 500 from nginx here

https://nginxpersona-kpendic.rhcloud.com/

thanks

**Comment by wrr** [comment]
Thank you for reporting the problem!

Just to make sure: after you edited  `./etc/site.conf` have you committed the change?

```
git commit -m "Set initial admin email" -a;
```

`./misc/rebuild` and `./misc/start_over` scripts do not do it automatically (although they probably could or they should at least issue a warning if there are not committed changes in the local repository).

**Comment by mkdizajn** [comment]
That's it :) :+1: 
I did overlooked that step.. 

thanks for help, keep up great work :)

**Comment by wrr** [comment]
7286faad29b0f413594a732ecfe21d920f803736 I've changed `rebuild` script to issue a warning and ask for confirmation if a local repository has uncommitted changes. This should prevent such omissions.
